// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIUOKNw84AvBpNwb_rO9unzhqZRuE4M3Y',
    appId: '1:749175189990:web:71ab68a642f4d9dc83a627',
    messagingSenderId: '749175189990',
    projectId: 'therental-test-9ae95',
    authDomain: 'therental-test-9ae95.firebaseapp.com',
    storageBucket: 'therental-test-9ae95.appspot.com',
    measurementId: 'G-HVKSDQXVRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaGanV0w39BDOVy8Muj6v6X2scHL7GR2Q',
    appId: '1:749175189990:android:cfee4c8e9448659f83a627',
    messagingSenderId: '749175189990',
    projectId: 'therental-test-9ae95',
    storageBucket: 'therental-test-9ae95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYXM04f1f4jsGPtjej0S9IrGnnPAL20eE',
    appId: '1:749175189990:ios:26f5b1440436058583a627',
    messagingSenderId: '749175189990',
    projectId: 'therental-test-9ae95',
    storageBucket: 'therental-test-9ae95.appspot.com',
    iosClientId:
        '749175189990-81isah1birrcbg0tflq4q7bsl3ve4f16.apps.googleusercontent.com',
    iosBundleId: 'com.example.therental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYXM04f1f4jsGPtjej0S9IrGnnPAL20eE',
    appId: '1:749175189990:ios:26f5b1440436058583a627',
    messagingSenderId: '749175189990',
    projectId: 'therental-test-9ae95',
    storageBucket: 'therental-test-9ae95.appspot.com',
    iosClientId:
        '749175189990-81isah1birrcbg0tflq4q7bsl3ve4f16.apps.googleusercontent.com',
    iosBundleId: 'com.example.therental',
  );
}
